name: API-Testing # Tên của workflow

on:
  push:
    branches:
      - main # Chạy kiểm thử khi có push lên nhánh main
  pull_request:
    branches:
      - main # Chạy kiểm thử khi có pull request đến nhánh main
  workflow_dispatch: # Cho phép kích hoạt thủ công từ giao diện GitHub

jobs:
  api-testing:
    runs-on: ubuntu-latest # Hoặc hệ điều hành bạn muốn

    steps:
    - name: Srouce code checkout
      uses: actions/checkout@v4

    - name: Node.js setup
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Hoặc phiên bản tương thích với Newman

    - name: Newman report
      run: npm install -g newman

    - name: Install HTML-Report
      run: npm install -g newman-reporter-htmlextra

    - name: Run getProducts collection
      run: |
        newman run getProducts.json \
          -d getProducts.csv \ 
          # --env-var "baseURL=https://api-with-bugs.practicesoftwaretesting.com" \ 
          --reporters cli,htmlextra \
          --reporter-htmlextra-export newman-reports/newman-report-collection1.html
      continue-on-error: true
    - name: Run postPutProducts collection
      run: |
        newman run postPutProducts.json \
          -d postputProducts.csv \ 
          # --env-var "baseURL=https://api-with-bugs.practicesoftwaretesting.com" \ 
          --reporters cli,htmlextra \
          --reporter-htmlextra-export newman-reports/newman-report-collection2.html
      continue-on-error: true
    - name: Upload newman reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: newman-reports
        path: newman-reports/